apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-other
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      securityContext:
        fsGroup: 2000
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: log-writer
          image: daraku/log-writer:v1.1
          volumeMounts:
            - name: shared-files
              mountPath: /files
          resources:
            limits:
              cpu: "25m"
              memory: "50Mi"
        - name: log-reader
          image: daraku/log-reader:v1.10
          volumeMounts:
            - name: shared-files
              mountPath: /files
          resources:
            limits:
              cpu: "25m"
              memory: "50Mi"
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: message