apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: log-output-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-output-dep
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 10
