apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-other
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: daraku/ping-pong:v1.12
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
          envFrom:
            - secretRef:
                name: ping-pong-secrets