apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-pong-go
  namespace: dwk-other
spec:
  template:
    metadata:
      name: ping-pong-go-v3
    spec:
      containers:
        - image: daraku/ping-pong-serverless:v1.0.3
          envFrom:
            - secretRef:
                name: ping-pong-secrets
          env:
            - name: PONG_PORT
              value: "8080"