apiVersion: v1
kind: Service
metadata:
  namespace: dwk-other
  name: ping-pong-svc
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5011
