apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-project
  name: project-nats-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: projet-nats
  template:
    metadata:
      labels:
        app: projet-nats
    spec:
      containers:
        - name: projet-nats
          image: gcr.io/PROJECT_ID/NATS_IMAGE
          env:
            - name: NATS_URL
              value: nats://my-nats.dwk-project.svc.cluster.local:4222
          envFrom:
            - secretRef:
                name: project-secrets