apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: dwk-project
  name: project-client-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-client
  strategy:
    canary:
      analysis:
        templates:
        - templateName: cpu-rate
        args:
        - name: current-namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      steps:
        - setWeight: 50
        - pause:
            duration: 5m
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: project-client
    spec:
      containers:
        - name: project-client
          image: gcr.io/PROJECT_ID/CLIENT_IMAGE
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"