apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-project
  name: project-client-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-client
  template:
    metadata:
      labels:
        app: project-client
    spec:
      containers:
        - name: project-client
          image: gcr.io/PROJECT_ID/CLIENT_IMAGE
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"