apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project-client-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: project-client-dep
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40
