apiVersion: v1
kind: Service
metadata:
  namespace: dwk-project
  name: project-client-svc
spec:
  type: NodePort
  selector:
    app: project-client
  ports:
    - port: 1233
      targetPort: 8089
      protocol: TCP