apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- server/manifests/deployment.yaml
- server/manifests/service.yaml
- client/manifests/deployment.yaml
- client/manifests/service.yaml
images:
- name: gcr.io/PROJECT_ID/CLIENT_IMAGE
  newName: daraku/project-client
- name: gcr.io/PROJECT_ID/SERVER_IMAGE
  newName: daraku/project-server