apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
resources:
- ../server/manifests/deployment.yaml
- ../server/manifests/service.yaml
- ../server/manifests/horizontalpodautoscaler.yaml
- ../client/manifests/deployment.yaml
- ../client/manifests/service.yaml
- ../client/manifests/horizontalpodautoscaler.yaml
- ../nats/manifests/deployment.yaml
- cronjob.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- statefulset.yaml
- analysistemplate.yaml
images:
- name: gcr.io/PROJECT_ID/CLIENT_IMAGE
  newName: gcr.io/main-nucleus-333615/project-client
  newTag: part-4-30448f459c94626ba2281592fa9796f1b44c8e37
- name: gcr.io/PROJECT_ID/SERVER_IMAGE
  newName: gcr.io/main-nucleus-333615/project-server
  newTag: part-4-30448f459c94626ba2281592fa9796f1b44c8e37
- name: gcr.io/PROJECT_ID/NATS_IMAGE
  newName: gcr.io/main-nucleus-333615/project-nats
  newTag: part-4-30448f459c94626ba2281592fa9796f1b44c8e37
