apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-project
  name: project-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-server
  template:
    metadata:
      labels:
        app: project-server
    spec:
      securityContext:
        fsGroup: 2000
      #affinity:
        # So that on deployment update the new pod can attach to the persistentvolumeclaim.
        # podAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #   - labelSelector:
        #       matchExpressions:
        #       - key: app
        #         operator: In
        #         values:
        #         - project-server
        #     topologyKey: "kubernetes.io/hostname"
      # volumes:
      #   - name: shared-files
      #     persistentVolumeClaim:
      #       claimName: shared-claim
      volumes:
        - name: cache
          emptyDir: {}
      containers:
        - name: project-server
          image: gcr.io/PROJECT_ID/SERVER_IMAGE
          envFrom:
            - secretRef:
                name: project-secrets
          volumeMounts:
            - name: cache
              mountPath: /files
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /health
               port: 8090
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
               path: /health
               port: 8090