apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-project
  name: project-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-server
  template:
    metadata:
      labels:
        app: project-server
    spec:
      securityContext:
        fsGroup: 2000
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: project-server
          image: gcr.io/PROJECT_ID/SERVER_IMAGE
          envFrom:
            - secretRef:
                name: project-secrets
          volumeMounts:
            - name: shared-files
              mountPath: /files