apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: dwk-project
  name: project-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-server
  strategy:
    canary:
      analysis:
        templates:
        - templateName: cpu-rate
        args:
        - name: current-namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      steps:
        - setWeight: 30
        - pause: { duration: 5m }
        - setWeight: 60
        - pause: { duration: 5m }
  template:
    metadata:
      labels:
        app: project-server
    spec:
      securityContext:
        fsGroup: 2000
      volumes:
        - name: cache
          emptyDir: {}
      containers:
        - name: project-server
          image: gcr.io/PROJECT_ID/SERVER_IMAGE
          env:
            - name: POSTGRES_URL
              value: "project-db-svc"
          envFrom:
            - secretRef:
                name: project-secrets
          volumeMounts:
            - name: cache
              mountPath: /files
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /health
               port: 8090
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
               path: /health
               port: 8090