apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-server-dep
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40
