name: Release project

on:
  push:
    branches:
      - master
    paths:
      - 'project/**'
      - '.github/workflows/gitops.yml'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GKE_SA_KEY }}

    - name: Build and Push nats
      uses: docker/build-push-action@v2
      with:
        context: project/nats
        push: true
        tags: "gcr.io/$PROJECT_ID/project-nats:$GITHUB_SHA"

    - name: Build and Push server
      uses: docker/build-push-action@v2
      with:
        context: project/server
        push: true
        tags: "gcr.io/$PROJECT_ID/project-server:$GITHUB_SHA"
    
    - name: Build and Push client
      uses: docker/build-push-action@v2
      with:
        context: project/client
        push: true
        tags: "gcr.io/$PROJECT_ID/project-client:$GITHUB_SHA"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: project/manifests
      run: |-
        kustomize edit set image gcr.io/PROJECT_ID/NATS_IMAGE=gcr.io/${{ $PROJECT_ID }}/project-nats:${{ github.sha }} && \
        kustomize edit set image gcr.io/PROJECT_ID/SERER_IMAGE=gcr.io/${{ $PROJECT_ID }}/project-server:${{ github.sha }} && \
        kustomize edit set image gcr.io/PROJECT_ID/CLIENT_IMAGE=gcr.io/${{ $PROJECT_ID }}/project-client:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'project/manifests/kustomization.yaml'
        message: New version release for gitops-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}